# Generated by Django 4.1.3 on 2022-12-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('name', models.AutoField(primary_key=True, serialize=False)),
                ('qtype', models.CharField(choices=[], max_length=2)),
                ('concept', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[], max_length=2)),
                ('text', models.TextField(max_length=500)),
                ('solution', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[], default='Student', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
