# Generated by Django 4.1.4 on 2022-12-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_questions_user_status_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ST', 'Student'), ('TA', 'Teaching Assistant'), ('IN', 'Instructor'), ('MT', 'Mentor'), ('AD', 'Admin')], default='Student', max_length=2),
        ),
    ]
