# Generated by Django 4.1.3 on 2022-12-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_questions_question_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choises',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('01', 'simple'), ('02', 'intermediate'), ('03', 'advanced ')], max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('MC', 'Multiple Choise'), ('MA', 'Matching'), ('TF', 'True False')], max_length=2),
        ),
    ]
