# Generated by Django 4.1.3 on 2022-12-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_question_choises_alter_question_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('MC', 'Multiple Choise'), ('MA', 'Matching'), ('TF', 'True False')], max_length=20),
        ),
    ]
