# Generated by Django 4.1.4 on 2022-12-26 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_question_qtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.TextField(default='text', max_length=255)),
                ('b', models.TextField(default='text', max_length=255)),
                ('c', models.TextField(default='text', max_length=255)),
                ('d', models.TextField(default='text', max_length=255)),
                ('e', models.TextField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd'), ('e', 'e')], default=models.TextField(default='text', max_length=255), max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('01', 'simple'), ('02', 'intermediate'), ('03', 'advanced ')], max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='choises',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.choise'),
        ),
    ]
