# Generated by Django 4.1.4 on 2022-12-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_choise_alter_question_qtype_alter_question_choises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choises',
            field=models.TextField(max_length=500),
        ),
    ]
