# Generated by Django 4.1.4 on 2022-12-26 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_question_choises'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choise',
        ),
    ]
