# Generated by Django 4.1.4 on 2022-12-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_delete_choise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(max_length=2),
        ),
    ]
