# Generated by Django 4.1.4 on 2022-12-26 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_question_level_alter_question_qtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='choises',
            new_name='choices',
        ),
    ]
