# Generated by Django 4.1.3 on 2022-12-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_question_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
