# Generated by Django 4.1.3 on 2022-12-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_choices_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
