# Generated by Django 4.1.3 on 2022-12-30 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_choices_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
    ]
