# Generated by Django 4.1.3 on 2022-12-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_choices_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='answer',
        ),
    ]
