# Generated by Django 4.1.3 on 2022-12-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_choices_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='question',
        ),
        migrations.AddField(
            model_name='choices',
            name='answer',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
