# Generated by Django 4.1.3 on 2022-12-30 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_choices_question_choices_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.question'),
            preserve_default=False,
        ),
    ]
