# Generated by Django 4.1.3 on 2023-01-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_choices_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quiz_or_sample',
            field=models.CharField(default='01', max_length=2),
            preserve_default=False,
        ),
    ]
