# Generated by Django 4.1.3 on 2023-01-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_question_quiz_or_sample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='a',
            new_name='choice_a',
        ),
        migrations.RenameField(
            model_name='choices',
            old_name='b',
            new_name='choice_b',
        ),
        migrations.RenameField(
            model_name='choices',
            old_name='c',
            new_name='choice_c',
        ),
        migrations.RenameField(
            model_name='choices',
            old_name='d',
            new_name='choice_d',
        ),
        migrations.RenameField(
            model_name='choices',
            old_name='e',
            new_name='choice_e',
        ),
    ]
